// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zeitung.Core.Context;


#nullable disable

namespace Zeitung.Worker.Migrations
{
    [DbContext(typeof(ZeitungDbContext))]
    [Migration("20251110012633_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zeitung.Worker.Data.ArticleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedSource")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FeedSource");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.HasIndex("PublishedDate");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("Zeitung.Worker.Data.ArticleTagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("ArticleId", "TagId")
                        .IsUnique();

                    b.ToTable("ArticleTags", (string)null);
                });

            modelBuilder.Entity("Zeitung.Worker.Data.TagCoOccurrenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer");

                    b.Property<int>("Tag1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Tag2Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Tag2Id");

                    b.HasIndex("Tag1Id", "Tag2Id")
                        .IsUnique();

                    b.ToTable("TagCoOccurrences", (string)null);
                });

            modelBuilder.Entity("Zeitung.Worker.Data.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Zeitung.Worker.Data.ArticleTagEntity", b =>
                {
                    b.HasOne("Zeitung.Worker.Data.ArticleEntity", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zeitung.Worker.Data.TagEntity", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Zeitung.Worker.Data.TagCoOccurrenceEntity", b =>
                {
                    b.HasOne("Zeitung.Worker.Data.TagEntity", "Tag1")
                        .WithMany("TagCoOccurrences1")
                        .HasForeignKey("Tag1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zeitung.Worker.Data.TagEntity", "Tag2")
                        .WithMany("TagCoOccurrences2")
                        .HasForeignKey("Tag2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tag1");

                    b.Navigation("Tag2");
                });

            modelBuilder.Entity("Zeitung.Worker.Data.ArticleEntity", b =>
                {
                    b.Navigation("ArticleTags");
                });

            modelBuilder.Entity("Zeitung.Worker.Data.TagEntity", b =>
                {
                    b.Navigation("ArticleTags");

                    b.Navigation("TagCoOccurrences1");

                    b.Navigation("TagCoOccurrences2");
                });
#pragma warning restore 612, 618
        }
    }
}
